# Generated by Django 3.1 on 2020-12-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.URLField(default='https://www.generationsforpeace.org/wp-content/uploads/2018/03/empty-300x240.jpg'),
        ),
    ]
