# Generated by Django 3.1 on 2020-12-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negade', '0003_auto_20201213_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
