# Generated by Django 3.1 on 2020-12-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negade', '0005_ads'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
