# Generated by Django 3.1 on 2020-12-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negade', '0006_delete_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost',
            field=models.PositiveIntegerField(),
            preserve_default=False,
        ),
    ]
