# Generated by Django 3.1 on 2020-12-16 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negade', '0008_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='negade.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='negade.vendor'),
        ),
    ]
