# Generated by Django 3.1 on 2020-12-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negade', '0009_auto_20201216_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover',
            field=models.URLField(default='https://www.generationsforpeace.org/wp-content/uploads/2018/03/empty-300x240.jpg'),
        ),
    ]
