# Generated by Django 3.1 on 2020-12-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negade', '0013_vendor_moto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribtion',
            new_name='Subscription',
        ),
    ]
