# Generated by Django 3.1 on 2020-12-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negade', '0014_auto_20201225_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
