# Generated by Django 3.1 on 2020-12-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negade', '0015_item_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='cost',
            new_name='price',
        ),
    ]
