# Generated by Django 3.1 on 2020-12-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negade', '0016_auto_20201227_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
