# Generated by Django 3.1 on 2020-12-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negade', '0017_remove_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
